title: Market Sentiment Analysis Dashboard
description: Real-time market sentiment analysis and tracking
baseurl: "/Edgar"
url: "https://theemeraldnetwork.github.io"

# Build settings
markdown: kramdown
include: 
  - "index.html"
  - "results/sentiment_report_latest.html"
exclude:
  - "*"
  - "**/*"
  - "!index.html"
  - "!results/sentiment_report_latest.html" 