title: Market Sentiment Analysis Dashboard
description: Real-time market sentiment analysis and tracking
baseurl: "/Edgar"
url: "https://theemeraldnetwork.github.io"

# Build settings
markdown: kramdown
include: 
  - "results/*.html"
  - "results/archive/reports/*.html"
exclude:
  - "*.py"
  - "*.pyc"
  - "*.csv"
  - "*.parquet"
  - "market/"
  - "database/"
  - "scripts/"
  - "utils/"
  - "logs/"
  - "backup/"
  - "requirements.txt"
  - "environment.yml"
  - "setup.py"
  - "check_environment.py"
  - "master_runner.py"
  - "README.md" 