title: Market Sentiment Analysis Dashboard
description: Real-time market sentiment analysis and tracking
baseurl: "/Edgar"
url: "https://theemeraldnetwork.github.io"

# Build settings
markdown: kramdown
include: [results]
exclude: [scripts, utils, database, logs, backup, "*.py", "*.pyc", "*.csv", "*.parquet", requirements.txt, environment.yml, setup.py, check_environment.py, master_runner.py, README.md] 