name: bayesian_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.20.0
  - scipy>=1.15.0
  - pandas>=2.0.0
  - arviz>=0.16.0
  - aesara-base>=2.9.0
  - pymc-core>=5.10.0
  - pip:
    - yfinance>=0.2.50
    - transformers>=4.40.0 